### ISSUE TITLE
Not working as should

### ISSUE THREAD

**Issue by vulnz** [OWASP/RiskAssessmentFramework#56]
Good day man.
thanks for project.
The problem on macos.
The thing is:
I did everything from the guide but still the project will only send by api project creation string but will not send any file for analysis as long as buttons do not work.

<img width="681" alt="изображение" src="https://user-images.githubusercontent.com/20043135/72961605-b81bc980-3dc2-11ea-8626-36c74a16c889.png">

**Comment by adeyosemanputra** [comment]
you should install sonarqube and sonar scanner by locally

**Comment by vulnz** [comment]
i did. does not change situation

**Comment by azharanees** [comment]
Hi @vulnz is it possible for you to post the error showed in the nodejs terminal

**Comment by vulnz** [comment]
npm start
( api) 
   at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by vulnz** [comment]
npm install
audited 659 packages in 2.829s
found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

if do fix - this is the result

**Comment by aramrami** [comment]
Azhar

Give him the required version of each software neeed to install RAF.

**Comment by azharanees** [comment]
@vulnz it is probably and issue with the version mismatch of the bcrypt 
try updating the binary too

`npm rebuild bcrypt --update-binary`

**Comment by azharanees** [comment]
> Azhar
> 
> Give him the required version of each software neeed to install RAF.

These versions were tested,

Sonarqube v7.9.1
Sonar-Scanner-cli v4.0.0^
mongodb v4.0^
nodejs v12^
